### ISSUE TITLE
Callbacks are not usable

### ISSUE THREAD

**Issue by Fayozjon** [metallurgical/jquery-metal-clone#1]
Trying to implement onComplete event function even console.log 
Nothing happening

**Comment by metallurgical** [comment]
Which release did you used? 
Check this out : https://github.com/metallurgical/jquery-metal-clone/releases

And try using latest release which is **1.2.0**

**Comment by metallurgical** [comment]
After checking the source, Seems like `minified` version is outdated as is not commit together with the latest release. If you're using the unminified version it is perfectly working fine for sure. Updating it now. You can try download latest release again.

**Comment by Fayozjon** [comment]
Thanks! Now its perfect.
Closing issue
