### ISSUE TITLE
Unique ID for name

### ISSUE THREAD

**Issue by izshreyansh** [metallurgical/jquery-metal-clone#10]
I think we should implement auto unique id for `name` attribute. Just the same way as it is for `id` attribute.

There are so many backend developers who would use something like this in their html.
```
<input name="attendees[0][first_name]" type="text">
<input name="attendees[1][first_name]" type="text">
<input name="attendees[2][first_name]" type="text">
```

What do you guys think?

**Comment by metallurgical** [comment]
Nice idea! Give me some time to implement it as lately got few things that blocking me. PR is welcome if you wish :)

**Comment by shreyanshpanchal** [comment]
I'll try to get it working & send a PR if i am successful. :)

**Comment by thapaPrabhat** [comment]
I need this too ..  

Did any one work on it ?

@izshreyansh ?

**Comment by izshreyansh** [comment]
@thapaPrabhat No man Sorry, I ended up using Vue after all.
