### ISSUE TITLE
removeBtn custom button

### ISSUE THREAD

**Issue by Fayozjon** [metallurgical/jquery-metal-clone#2]
Can you add on next version such option?
For making REMOVE button as defined element without clonin it.
For example 

[Add row .cloneBtn]     [Remove row .removeBtn]

**Comment by metallurgical** [comment]
i'm thinking about this before during development, but encounter a few problems on remove element part. Removing element no longer in your/user control, which means, if only have one remove button without cloning it per cloned elements, removing element only can be done in sequence order either from top to bottom or bottom to top as script doesn't know which element need to remove. Differ with per-cloned element's remove button, as user can choose which element to remove. 

I guess i need to add this functionality back into plugins :+1:
