### ISSUE TITLE
Exceptions for the copyValue parameter (false)

### ISSUE THREAD

**Issue by jeffersondevasconcelos** [metallurgical/jquery-metal-clone#8]
copyValue is a very hard parameter and sometimes you may want to keep values ​​of certain elements, with for example, hidden fields.

To fit your beautiful plugin to my needs, I created a new parameter for it: clearExceptions

(...)
`currentClearExceptions = opt.clearExceptions,`
(...)
```
function clearForm (container) {
  container.find ('input: not (input [type = button], input [type = submit], input [type = checkbox], input [type = radio] "), textarea, select' ) {
    $ (this) .not (currentClearExceptions) .val ('');
  });
}
```
(... fn.metalClone.defaults)
`clearExceptions: '', // Make exception for elements that you do not want to clear`

Where can I pass the new option informing the name of the elements of which I want to keep a copy of the value

Example:

```
$ ('. group'). metalClone ({
  btnClone: ​​'# btnAdd',
  copyValue: false,
  clearExceptions: '#current_user_id',
  enableAnimation: false,
});
```

**Comment by metallurgical** [comment]
Great idea! it would be a pleasure if you could fork this repo and send me pull request. Then later, i'll merge into master branch. So anyone using this plugin can get benefit from it.

**Comment by metallurgical** [comment]
Refer to #9
